parameters:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
<<<<<<< HEAD
  displayName: 'Build the project - ${{ parameters.buildConfiguration }}'
=======
  displayName: 'dotnet build ${{ parameters.buildConfiguration }}'
>>>>>>> Support build configurations
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
    projects: '**/*.csproj'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish ${{ parameters.buildConfiguration }}'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: true
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.BuildConfiguration }}'
    zipAfterPublish: true